## YAML Template.
spring:
  profiles:
    active: local
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: docker
server:
  port: 10000
# zuul routes
zuul:
  routes:
    simpleservice: /simple/**
    simplefooservice: /foo/**


---
spring:
  profiles: local
server:
  port: 10000
# zuul routes
zuul:
  routes:
    simpleservice: /simple/**
    simplefooservice: /foo/**

