## YAML Template.
spring:
  profiles:
    active: docker
---
spring:
  profiles: docker
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
