## docker compose file with docker build

eureka:
    hostname: eureka
    build: ../eureka/target
    ports: 
        - "8761:8761"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DISCOVERY_HOSTNAME=eureka
        - DISCOVERY_PORT=8761
        - DISCOVERY_PEER_HOSTNAME=eureka_peer
        - DISCOVERY_PEER_PORT=8762
        
eureka_peer:
    hostname: eureka_peer
    build: ../eureka/target
    ports: 
        - "8762:8762"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DISCOVERY_HOSTNAME=eureka_peer
        - DISCOVERY_PORT=8762
        - DISCOVERY_PEER_HOSTNAME=eureka
        - DISCOVERY_PEER_PORT=8761

config:
    hostname: configserver
    build: ../config-service/target
    links:
       - eureka
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        
sidecar:
    hostname: sidecar
    build: ../sidecar-service/target
    ports:
        - "10000:10000"
    links:
        - eureka
        - simpleservice
    environment:
        - SPRING_PROFILES_ACTIVE=docker
  
simpleservice:
    hostname: simpleservice
    build: ../simple-service/target
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    links: 
        - eureka
                       
simplesubservice:
    hostname: simplesubservice
    build: ../simple-sub-service/target
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    links:
        - eureka
    
