## docker compose file with docker build

eureka:
    hostname: eureka
    build: ../eureka/target
    ports: 
        - "8761:8761"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        
config:
    hostname: configserver
    build: ../config-service/target
    links:
       - eureka
    environment:
        - SPRING_PROFILES_ACTIVE=docker
  
simpleservice:
    hostname: simpleservice
    build: ../simple-service/target
    ports: 
        - "8080:8080"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    links: 
        - eureka
                       
simplesubservice:
    hostname: simplesubservice
    build: ../simple-sub-service/target
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    links:
        - eureka
    
