## YAML Template.
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  cloud:
    config:
      discovery:
        enabled: true
---
spring:
  profiles: docker
---
spring:
  profiles: local
