consulserver:
  image: gliderlabs/consul-server:latest
  hostname: consulserver
  ports:
  - "8300"
  - "8400"
  - "8500:8500"
  - "53"
  command: -data-dir /tmp/consul -bootstrap -client 0.0.0.0

# listen on local docker sock to register the container with public ports to the consul service
registrator:
  image: gliderlabs/registrator:master
  hostname: registrator
  links:
  - consulserver:consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  command: -internal consul://consul:8500
  #command: consul://consul:8500

sidecar:
    hostname: sidecar
    build: ../sidecar-service/target
    ports:
        - "10000:10000"
    links:
        - consulserver:consul
        - simpleservice
    environment:
        - SPRING_PROFILES_ACTIVE=docker
  
simpleservice:
    hostname: simpleservice
    build: ../simple-service/target
#    ports: 
#        - "8080:8080"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    links: 
        - consulserver:consul
                       
simplesubservice:
    hostname: simplesubservice
    build: ../simple-sub-service/target
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    links:
        - consulserver:consul
    
