## YAML Template.
spring:
  profiles:
    active: docker
---
spring:
  profiles: docker
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
