## YAML Template.
spring:
  profiles:
    active: local
#eureka:
#  instance:
#    preferIpAddress: true
#ribbon:
#  eureka:
#    enabled: true
---
spring:
  profiles: docker
my:
    property: foo_docker
---
spring:
  profiles: local
my:
    property: foo_docker
---
my:
    default: default
