## YAML Template.
spring:
  profiles:
    active: docker
---
spring:
  profiles:
    name: docker
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/xdoo/docker-spring-demo-config
        health:
          repositories:
            movie:
              label: master
              profiles: docker
            rating:
              label: master
              profiles: docker
server:
  port: 8888
info:
  description: Config Server
  url: https://github.com/xdoo/docker-spring-demo-config
